server:
  port: 8762
zuul:
  routes:
    accounting-service:
      path: /accounting/**
      serviceId: accounting-service
    catalog-service:
      path: /catalog/**
      serviceId: catalog-service
    payment-service:
      path: /pay/**
      serviceId: payment-service

spring:
  application:
    name: gateway-service


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

